### ISSUE TITLE
Document EC-provided custom rego functions

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1072]
### **Description**

Let's come up with a way that we can easily document custom rego functions introduced by EC, e.g. the one from https://github.com/enterprise-contract/ec-cli/issues/1070.

It should be clear to users how to use the function. (Expected parameters, expected return values, how it behaves, etc)

### **Acceptance Criteria**

- The `ec.fetch_oci_blob` function is documented somewhere on  [enterprisecontract.dev](https://enterprisecontract.dev/).

**Comment by zregvart** [comment]
Do we need `ec policy test` command?

**Comment by lcarva** [comment]
https://enterprisecontract.dev/docs/ec-cli/main/rego.html
