### ISSUE TITLE
Document how to debug antora extensions

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1464]
This repo defines a couple of antora extensions that are used during the website build, [[reference-antora-extension](https://github.com/enterprise-contract/ec-cli/tree/main/reference-antora-extension)], [rego-antora-extension](https://github.com/enterprise-contract/ec-cli/tree/main/rego-antora-extension), and [tekton-task-antora-extension](https://github.com/enterprise-contract/ec-cli/tree/main/tekton-task-antora-extension).

When making a change to these extensions, I don't know how to try out my changes in order to verify they are working properly.

**Acceptance Criteria**

* Document the process of executing antora extensions locally. Ideally, this includes executing them as part of a local website build.

**Comment by zregvart** [comment]
I thought documenting this on the website end would be better option, here is a [PR](https://github.com/enterprise-contract/enterprise-contract.github.io/pull/240) for that.
