### ISSUE TITLE
Add tests for the antora extensions

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1465]
Let's make sure we have some basic coverage for the code defined in the antora extensions in this repo.

**Acceptance Criteria**

* Write basic tests to verify the functionality of the antora extensions in this repo.
* These tests should run as part of the CI in this repo. (If this turns out to be too much of an effort, consider splitting this item into another issue.)

**Comment by zregvart** [comment]
Closed in favor of EC-513
