### ISSUE TITLE
[BUG] ec validate fails on artifact with multiple signatures

### ISSUE THREAD

**Issue by ralphbean** [enterprise-contract/ec-cli#1698]
## Describe the Bug

_A clear and concise description of what the bug is, ideally within a sentence or two._

ec validate complains that the image is not signed, but I'm pretty sure it is.

I confirmed that the image is signed with `cosign tree quay.io/rbean/testing:granite-8b-code-instruct`. Notice also that it has multiple copies of the same signature. Is cosign tripping up on that?

## Steps to Reproduce

```
❯ IMAGE=quay.io/rbean/testing:granite-8b-code-instruct
❯ ec validate image --image ${IMAGE} --ignore-rekor --policy github.com/enterprise-contract/config//redhat --public-key <(echo "${KONFLUX_PUBLIC_KEY}") --info --output=text
```

## Expected Behavior

I expect the validation to show me errors about not using the buildah task.

## Actual Behavior

I see errors indicating that the image is not signed.

## Environment Details

This is using the latest ec-cli, downloaded today.

**Comment by ralphbean** [comment]
No, it doesn't seem to be about the multiple signatures. Check out quay.io/rbean/testing:granite-8b-code-instruct-2 which is a better, simpler test case.

**Comment by simonbaird** [comment]
Not sure if it's changed, but I don't see any cosign signatures on quay.io/rbean/testing:granite-8b-code-instruct-2.

```
$ cosign tree quay.io/rbean/testing:granite-8b-code-instruct-2
... No Supply Chain Security Related Artifacts artifacts found for image ...
```

**Comment by ralphbean** [comment]
I figured it out. The problem is that the thing I am trying to verify is an image index, but none of the image manifests were exposed to chains, so none of them got signed. The image index was signed, but not the image manifests. If I alter my task to expose all the pullspecs, then chains will sign them all and I can make progress with ec validation.

Thanks!
