### ISSUE TITLE
Custom Rego function to fetch files from images

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-cli#1788]
In policy we evaluate content of image files. For example the OLM bundle manifests or the CycloneDX SBOM files. For this we rely on [OCI file fetchers](https://github.com/enterprise-contract/ec-cli/tree/main/internal/fetchers/oci/files). For greater flexibility, that is, moving the logic that determines when and what files are extracted and provided as input, a custom Rego function (e.g. `ec.oci.file`) would be better. This way the logic of when to extract a file and what files to extract can be governed by the policy implementation.

A/C:
* Custom rego function exists to fetch files from images
* Image ref requires full digest (i.e. it's pinned)
* Sufficient test coverage
* The usual documentation is generated

**Comment by ralphbean** [comment]
FYI, I've got some images based on https://github.com/containers/ai-lab-recipes that are just enormous (30GB, many of them in a single Konflux snapshot). When I try to evaluate them with ec, their `vendor` label causes ec to pull the images in order to check for the contents of a file on the filesystem. This takes hours, and is not worth it.

I'd love it if I could turn this off by omitting the rule from the ec policy I'm using.

**Comment by zregvart** [comment]
Could change [this condition](https://github.com/enterprise-contract/ec-cli/blob/4a26f136d707f35c0c3dce8b857a3ff3b06585ca/internal/fetchers/oci/files/rhmanifest.go#L41) for that use cases, is there a label we can use to filter out these images?

**Comment by ralphbean** [comment]
> is there a label we can use to filter out these images?

Unsure, but we could add any label if its reasonable.

Here are the current labels on one of them:

```
{
  "architecture": "x86_64",
  "build-date": "2024-07-30T16:09:48",
  "containers.bootc": "1",
  "image_version_id": "1.1.0",
  "io.buildah.version": "1.37.0-dev",
  "org.opencontainers.image.source": "https://gitlab.com/path/to/some/repo.git",
  "org.opencontainers.image.vendor": "Red Hat, Inc.",
  "org.opencontainers.image.version": "9.20240714.0",
  "ostree.bootable": "true",
  "ostree.commit": "f2eddc4d54c4af0e93c9648b178239bf829fc40d75f68ecdd1082e9138d91e50",
  "ostree.final-diffid": "sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1",
  "ostree.linux": "1.2.3.4",
  "redhat.compose-id": "",
  "redhat.id": "rhel",
  "redhat.version-id": "9.4",
  "rpmostree.inputhash": "8ddf63b159beba2d783cadbc7d2f39acead19b0eea7f3af4a84fd0d39c954c4e",
  "vcs-ref": "7be34e36e243a9200fe82fa4b36201d39f78e258",
  "vcs-type": "git",
  "vendor": "Red Hat, Inc."
}
```
