### ISSUE TITLE
Stop download Red Hat manifests from the image

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#1894]
Once https://github.com/enterprise-contract/ec-policies/issues/1115 is completed and enough time has passed for users to adopt it, the EC cli no longer needs to download the Red Hat manifests from the image. The rego will do it if needed.

**Acceptance Criteria**
* EC cli no longer downloads Red Hat manifests from within the image.

**Comment by zregvart** [comment]
Fixed via https://github.com/enterprise-contract/ec-cli/pull/1986
