### ISSUE TITLE
[Feature] Make effective_on date for "ec track bundle" configurable

### ISSUE THREAD

**Issue by ralphbean** [enterprise-contract/ec-cli#1934]
## Describe the Feature

I think I'd like the effective_on date for "ec track bundle" to be configurable via a command line option.

Really, I'd like to double it from 30 days to 60 days, but rather than seek a change in ec-cli every time we want to change it, it would be nice if the default was 30 days, but we could invoke it with an argument in the build-definitions repo to use a longer date there.

Remember some of the reasoning behind design decisions in Konflux? We wanted a PR model for pipeline definitions, so that a team could ignore those updates for a period of time while they stabilize for a release, and then only merge pipeline definitions updates later after their stressful release cycle was done. Today, with a "short" 30 day window, team's don't quite get that experience. They may update their pipeline one day, and then try to stabilize their product for release for 31 days (ignoring pipeline update PRs all the while). Then, they find that suddenly they _have_ to accept the update. Doubling the period to 60 days makes sense to me.

**Comment by lcarva** [comment]
@ralphbean, :+1:  the requested feature makes sense. 

I just want to make sure how expiration dates behave is understood. The expiration date is a property of the data. It is not configurable via an ECP. So if different developers want different expiration dates, different data sources are needed.

**Comment by lcarva** [comment]
I'm wondering if this new parameter should be a timestamp, e.g. `2024-09-30T00:00:00Z`,  or a duration, e.g. `30days`.

I think a duration probably makes more sense here.

**Comment by lcarva** [comment]
Walking back on my previous comment. It looks like the largest unit supported by duration parsing is hours. Having to always multiply expected days by 8 seems like a bad user experience. Let's just allow users to provide a timestamp as that gives the most flexibility.

NOTE: The [proposal](https://www.github.com/golang/go/issues/11473) to support days unit was previously rejected.

**Comment by zregvart** [comment]
Perhaps we can say in all cases, the duration provided is in days, i.e. have the option be named `--in-effect-days`?
