### ISSUE TITLE
Replace the use of github.com/hashicorp/go-multierror with errors.Join

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-cli#1971]
We don't really need github.com/hashicorp/go-multierror any more, from golang 1.20 we can use [errors.Join](https://pkg.go.dev/errors#Join) instead. One less dependency to worry about...

**Comment by lcarva** [comment]
I wonder if `errors.Join` could also be used [here](https://github.com/enterprise-contract/ec-cli/blob/7f410ec2d1a3bdfb6f5bf9a1a3434e4f463ba97d/internal/output/output.go#L337). It would make [these](https://github.com/enterprise-contract/ec-cli/blob/7f410ec2d1a3bdfb6f5bf9a1a3434e4f463ba97d/internal/output/output_test.go#L831-L834) tests simpler.
