### ISSUE TITLE
Introduce policy rule file fetch annotation

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-cli#937]
The EC CLI can now fetch files from the image being validated and feed that to the policy-input. That's been helpful in addressing some use cases.

In order to avoid pulling every image that EC validates, certain files are only fetched depending on certain image labels. See docs [here](https://enterprisecontract.dev/docs/ec-cli/main/policy_input.html).

However, this is not ideal. The files should only be fetched if there's actually a policy rule that needs them. 

Let's invert things a little bit. Let's introduce a rego package annotation that states that the policy rules in a certain package want a certain file from the image. Then, let's teach the ec cli to look at those annotations in order to decide which files to fetch. If the file is not found, that's ok. The policy rules are responsible for verifying this.

NOTE: Kudos to Zoran for coming up with this idea.

## Acceptance Criteria

 * Files are only fetched from an image if there are policy rules that require such files.

**Comment by joejstuart** [comment]
test

**Comment by zregvart** [comment]
An additional problem with the annotation comes from the fact that annotations are static metadata, at runtime a rule might never reach the point where it needs the files. So mere inclusion of the rule would cause the files to be fetched even though they might not be examined by the rule.

**Comment by lcarva** [comment]
@zregvart, that's an excellent point. One thing to keep in mind as well is that ec-cli is responsible for determining if a package/rule is included. That could be helpful here.

**Comment by lcarva** [comment]
Issue for adding this behavior to conftest: https://github.com/open-policy-agent/conftest/issues/856
