### ISSUE TITLE
Today ec validate image task accepts policy configuration as CR or inline not the URL for policy

### ISSUE THREAD

**Issue by savitaashture** [enterprise-contract/ec-cli#964]
Usecase:

when we use [verify-enterprise-contract](https://github.com/enterprise-contract/ec-cli/blob/main/tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml#L45 ) the only way to provide policy is via CR or inline as per the doc

But if we use CR then there will be a prerequisite for CR availability on that cluster.

So along with CR and inline it would be nice if EC support providing URL for policy yaml 
ex: https://gist.githubusercontent.com/savitaashture/574a85f799626d25a36c47c71fbda234/raw/4ef554003eeace9fc5987192a30e92ed36eb138e/policy.yaml

It will be more useful

**Comment by simonbaird** [comment]
AIUI the request is for a https://some-http-host/path/policy.yaml value to be parsed as a fetch and downloaded. Already we do support an equivalent git://some-git-host/path/policy.yaml, but it appears the https fetch doesn't work as expected. A workaround for the exact issue reported here would be to figure out the git:// url for the gist, but let's make sure the https fetch works as a user would expect it to.
